In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3,4,5])

In [3]:
arr1

array([1, 2, 3, 4, 5])

In [4]:
print(arr1)

[1 2 3 4 5]


In [5]:
type(arr1)

numpy.ndarray

In [6]:
arr1.ndim

1

In [7]:
arr1.size

5

In [9]:
len(arr1)

5

In [3]:
l2 = [[1,2,3],[4,5,6]]

In [2]:
type(l2)

list

In [4]:
l2

[[1, 2, 3], [4, 5, 6]]

In [4]:
import numpy as np


In [10]:
arr2 = np.array(l2)

In [11]:
arr2


array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
print(arr2)

[[1 2 3]
 [4 5 6]]


In [13]:
type(arr2)

numpy.ndarray

In [14]:
arr2.ndim

2

In [15]:
arr2.size

6

In [16]:
l3 = [[1,2,3],[4,5,6]]

In [17]:
len(l2)

2

In [20]:
arr3 = np.array([[1,2,3],[4,5,6]])

In [21]:
arr3.size

6

In [22]:
len(arr3)

2

In [23]:
arr3.dtype

dtype('int32')

In [24]:
arr3

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
arr3.shape

(2, 3)

In [26]:
arr4 = np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,0],[1,2]]])

In [27]:
print(arr4)

[[[1 2]
  [3 4]
  [5 6]]

 [[7 8]
  [9 0]
  [1 2]]]


In [28]:
arr4.size

12

In [29]:
arr4.ndim

3

In [30]:
arr4.dtype

dtype('int32')

In [31]:
arr4.shape

(2, 3, 2)

In [32]:
len(arr4)

2

In [1]:
l3 = [1,2,3,4,5]

In [5]:
arr5 = np.array(l3)

In [6]:
arr5

array([1, 2, 3, 4, 5])

In [7]:
arr5.shape

(5,)

In [8]:
arr5.ndim

1

In [9]:
l1 = [1,2,3,4,5]

In [10]:
l1 + 10

TypeError: can only concatenate list (not "int") to list

In [11]:
l1 + [10]

[1, 2, 3, 4, 5, 10]

In [12]:
arr6 = np.array(l1)

In [13]:
arr6

array([1, 2, 3, 4, 5])

In [14]:
arr6 + 10

array([11, 12, 13, 14, 15])

In [19]:
arr6 % 2 == 0

array([False,  True, False,  True, False])

In [20]:
out = arr6 % 2 == 0

In [21]:
out

array([False,  True, False,  True, False])

In [22]:
out.dtype

dtype('bool')

In [23]:
out = arr6 > 3

In [24]:
out

array([False, False, False,  True,  True])

In [25]:
a1 = np.arange(10,20,3)

In [26]:
a1

array([10, 13, 16, 19])

In [27]:
list(range(10,20,3))

[10, 13, 16, 19]

In [28]:
range(2,5,0.5)

TypeError: 'float' object cannot be interpreted as an integer

In [29]:
a1 = np.arange(2,5,0.5)

In [30]:
a1

array([2. , 2.5, 3. , 3.5, 4. , 4.5])

In [31]:
a1.dtype

dtype('float64')

In [32]:
np.arange(10,5,-1)

array([10,  9,  8,  7,  6])

In [33]:
np.arange("01.03.2024","31.03.2024")

TypeError: arange() not supported for inputs with DType <class 'numpy.dtypes.StrDType'>.

In [39]:
np.arange("01-03-2024","31-03-2024", dtype = 'datetime64[D]')

ValueError: Error parsing datetime string "01-03-2024" at position 8

In [38]:
np.arange("2024-03-01","2024-03-31", dtype='datetime64[D]')

array(['2024-03-01', '2024-03-02', '2024-03-03', '2024-03-04',
       '2024-03-05', '2024-03-06', '2024-03-07', '2024-03-08',
       '2024-03-09', '2024-03-10', '2024-03-11', '2024-03-12',
       '2024-03-13', '2024-03-14', '2024-03-15', '2024-03-16',
       '2024-03-17', '2024-03-18', '2024-03-19', '2024-03-20',
       '2024-03-21', '2024-03-22', '2024-03-23', '2024-03-24',
       '2024-03-25', '2024-03-26', '2024-03-27', '2024-03-28',
       '2024-03-29', '2024-03-30'], dtype='datetime64[D]')

In [40]:
np.arange("2024-03-01","2024-04-01", dtype='datetime64[D]')

array(['2024-03-01', '2024-03-02', '2024-03-03', '2024-03-04',
       '2024-03-05', '2024-03-06', '2024-03-07', '2024-03-08',
       '2024-03-09', '2024-03-10', '2024-03-11', '2024-03-12',
       '2024-03-13', '2024-03-14', '2024-03-15', '2024-03-16',
       '2024-03-17', '2024-03-18', '2024-03-19', '2024-03-20',
       '2024-03-21', '2024-03-22', '2024-03-23', '2024-03-24',
       '2024-03-25', '2024-03-26', '2024-03-27', '2024-03-28',
       '2024-03-29', '2024-03-30', '2024-03-31'], dtype='datetime64[D]')

In [41]:
np.arange("2024-03-01","2024-06-01", 7, dtype='datetime64[D]')

array(['2024-03-01', '2024-03-08', '2024-03-15', '2024-03-22',
       '2024-03-29', '2024-04-05', '2024-04-12', '2024-04-19',
       '2024-04-26', '2024-05-03', '2024-05-10', '2024-05-17',
       '2024-05-24', '2024-05-31'], dtype='datetime64[D]')

In [42]:
np.arange("2024-03-01","2024-06-01", 1, dtype='datetime64[M]')

array(['2024-03', '2024-04', '2024-05'], dtype='datetime64[M]')

In [43]:
np.arange("2024-03-01","2024-06-01", 1, dtype='datetime64[W]')

array(['2024-02-29', '2024-03-07', '2024-03-14', '2024-03-21',
       '2024-03-28', '2024-04-04', '2024-04-11', '2024-04-18',
       '2024-04-25', '2024-05-02', '2024-05-09', '2024-05-16',
       '2024-05-23'], dtype='datetime64[W]')

In [2]:
np.random.randint(10,30,(10,))

array([11, 19, 19, 14, 26, 18, 10, 24, 17, 20])

In [3]:
np.random.randint(10,30,(10,))

array([14, 25, 21, 21, 22, 14, 24, 11, 15, 11])

In [4]:
np.random.randint(1,9,(3,4))

array([[7, 1, 3, 7],
       [7, 4, 3, 1],
       [7, 5, 6, 3]])

In [5]:
np.random.randint(1,9,(3,2,4))

array([[[4, 7, 4, 4],
        [8, 4, 6, 3]],

       [[7, 3, 6, 5],
        [4, 5, 5, 5]],

       [[4, 2, 5, 2],
        [4, 2, 3, 8]]])

In [6]:
np.random.rand(3,4)

array([[0.23942845, 0.27076657, 0.62955016, 0.03913376],
       [0.5442665 , 0.76033039, 0.90760124, 0.31419626],
       [0.81423799, 0.20788001, 0.13989836, 0.55205355]])

In [7]:
np.random.rand(6)

array([0.97897504, 0.37003886, 0.32010982, 0.36951362, 0.57188888,
       0.51329847])

In [8]:
np.random.rand(3,2,3)

array([[[0.18882538, 0.87032007, 0.08733269],
        [0.15608076, 0.09776822, 0.69871587]],

       [[0.65522121, 0.37678048, 0.14852444],
        [0.71774253, 0.74314697, 0.51728831]],

       [[0.04663682, 0.94578677, 0.28628737],
        [0.00972448, 0.42660924, 0.23658114]]])

In [9]:
np.random.randn(3,2)

array([[ 1.58327437,  1.43312828],
       [-1.1085385 , -0.95161145],
       [ 0.09890525, -0.12049076]])

In [10]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
np.zeros((3,4),dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [12]:
np.ones((3,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [13]:
np.full((3,4),5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [4]:
arr1 = np.random.randint(0,9,(5,))

In [10]:
arr3 = np.random.randint(0,10,(4,))

In [6]:
arr2 = np.random.randint(0,9,(5,))

In [7]:
arr1

array([4, 7, 2, 2, 2])

In [8]:
arr2

array([0, 4, 4, 0, 1])

In [11]:
arr3

array([0, 0, 8, 4])

In [14]:
arr1 > arr2

array([ True,  True, False,  True,  True])

In [13]:
arr1 > arr3

ValueError: operands could not be broadcast together with shapes (5,) (4,) 

In [15]:
arr4 = np.random.randint(0,9,(3,4))

In [16]:
arr4

array([[2, 1, 7, 5],
       [4, 3, 5, 7],
       [3, 8, 1, 5]])

In [17]:
arr5 = np.random.randint(0,9,(3,4))

In [18]:
arr5

array([[8, 4, 5, 4],
       [7, 7, 1, 8],
       [0, 2, 6, 2]])

In [19]:
arr4 + arr5

array([[10,  5, 12,  9],
       [11, 10,  6, 15],
       [ 3, 10,  7,  7]])

In [20]:
arr4 - arr5

array([[-6, -3,  2,  1],
       [-3, -4,  4, -1],
       [ 3,  6, -5,  3]])

In [21]:
arr4 * arr5

array([[16,  4, 35, 20],
       [28, 21,  5, 56],
       [ 0, 16,  6, 10]])

In [24]:
m1 = np.array([[3,1,1],
             [2,1,1]])

In [25]:
m2 = np.array([[2,1],
              [3,0],
              [2,4]])

In [26]:
m1

array([[3, 1, 1],
       [2, 1, 1]])

In [27]:
m2

array([[2, 1],
       [3, 0],
       [2, 4]])

In [28]:
m1 @ m2

array([[11,  7],
       [ 9,  6]])