In [1]:
 len(['A','B',1])

3

In [2]:
len([sum([1,1,1])])

1

In [3]:
L=[1,3,2]

sorted(L) 

[1, 2, 3]

In [4]:
def print_function(A):
    for a in A:
        print(a + '1')
print_function(['a', 'b', 'c'])

a1
b1
c1


In [1]:
x = 5 
while x != 2: 
    print(x) 
    x = x - 1 

5
4
3


In [2]:
for i, x in enumerate(['A', 'B', 'C']): 
    print(i, 2 * x)


0 AA
1 BB
2 CC


In [3]:
class Points(object): 
    def __init__(self, x, y): 
        self.x = x 
        self.y = y 
    def print_point(self): 
        print('x=', self.x, ' y=', self.y) 


p2 = Points(1, 2) 
p2.x = 'A' 
p2.print_point()


x= A  y= 2


In [4]:
 a = 1 
def do(x): 
    a = 100 
    return x + a 


print(do(1))

101


In [5]:
try:
    numerator = 10
    denominator = 0
    result = numerator / denominator
    print(result)
except ZeroDivisionError:
    print("Error: Denominator cannot be 0.")

Error: Denominator cannot be 0.


In [6]:
a=np.array([0,1]) 

b=np.array([1,0]) 

np.dot(a,b) 

NameError: name 'np' is not defined

In [7]:
import numpy as np

In [8]:
a=np.array([0,1]) 

b=np.array([1,0]) 

np.dot(a,b) 

0

In [9]:
X=np.array([[1,0,1],[2,2,2]]) 

out=X[0:2,2]

In [10]:
out

array([1, 2])

In [12]:
X=np.array([[1,0],[0,1]])

Y=np.array([[2,2],[2,2]]) 

Z=np.dot(X,Y) 

In [13]:
Z

array([[2, 2],
       [2, 2]])

In [15]:
2//1

2

1//2 

In [16]:
1//2

0

In [17]:
a= '1,2,3,4'.split(',')

In [18]:
a

['1', '2', '3', '4']

In [19]:
a=np.array([0,1,0,1,0]) 

b=np.array([1,0,1,0,1]) 

a*b 

array([0, 0, 0, 0, 0])

In [20]:
a=np.array([1,1,1,1,1]) 

a+1

array([2, 2, 2, 2, 2])